apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-aspnetcore-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-aspnetcore-pod
  template:
    metadata:
      labels:
        app: hello-aspnetcore-pod
    spec:
      containers:
        - name: hello-aspnetcore-container
          image: exploredocker254.azurecr.io/userregistration:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
